# Generated by Django 6.0.7 on 2026-07-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dismissedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
