# Generated by Django 6.0.7 on 2026-07-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_awsaccount_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awsaccount',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='awsaccount',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
